// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ySbZqhUxw0GYmiN0Iykk4YR8Mx7xFgk',
    appId: '1:676771983076:web:c685de46373196df4346f1',
    messagingSenderId: '676771983076',
    projectId: 'tinder-app-3efc3',
    authDomain: 'tinder-app-3efc3.firebaseapp.com',
    storageBucket: 'tinder-app-3efc3.firebasestorage.app',
    measurementId: 'G-E77D384NXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjXp12QhR9swdAMFwYEEd_QCHkx4aiS-w',
    appId: '1:676771983076:android:fd2fd3ef88fc99e94346f1',
    messagingSenderId: '676771983076',
    projectId: 'tinder-app-3efc3',
    storageBucket: 'tinder-app-3efc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNi460lOQbuchzzAcBFytxpiqQjiPXRw4',
    appId: '1:676771983076:ios:20c9decd1cf27c844346f1',
    messagingSenderId: '676771983076',
    projectId: 'tinder-app-3efc3',
    storageBucket: 'tinder-app-3efc3.firebasestorage.app',
    iosBundleId: 'com.example.tinderYt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNi460lOQbuchzzAcBFytxpiqQjiPXRw4',
    appId: '1:676771983076:ios:20c9decd1cf27c844346f1',
    messagingSenderId: '676771983076',
    projectId: 'tinder-app-3efc3',
    storageBucket: 'tinder-app-3efc3.firebasestorage.app',
    iosBundleId: 'com.example.tinderYt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ySbZqhUxw0GYmiN0Iykk4YR8Mx7xFgk',
    appId: '1:676771983076:web:1d300095217fa5304346f1',
    messagingSenderId: '676771983076',
    projectId: 'tinder-app-3efc3',
    authDomain: 'tinder-app-3efc3.firebaseapp.com',
    storageBucket: 'tinder-app-3efc3.firebasestorage.app',
    measurementId: 'G-3SD0HHFG9J',
  );
}
